#!/usr/bin/env bash
# Install Flatpal to user-local XDG paths. Reversible via uninstall.sh.
set -u

SRC_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

PREFIX="${HOME}/.local"
BIN_DIR="${PREFIX}/bin"
APP_DIR="${PREFIX}/share/flatpal"
PKG_DIR="${APP_DIR}/flatpal"
DESKTOP_DIR="${PREFIX}/share/applications"
ICON_HICOLOR="${PREFIX}/share/icons/hicolor"

# All available sizes ship in data/ as flatpal-icon-<size>x<size>.png. We
# install each to its matching hicolor directory so GTK and GNOME Shell pick
# the native-size icon for whichever surface they're drawing — no scaling,
# no pixelation on small surfaces like the taskbar. Set covers the full
# freedesktop hicolor advertised list for application icons.
ICON_SIZES=(16 24 32 48 64 96 128 192 256 512)

mkdir -p "${BIN_DIR}" "${APP_DIR}" "${DESKTOP_DIR}"

# Replace the package directory cleanly so removed files don't linger.
rm -rf "${PKG_DIR}"
cp -r "${SRC_DIR}/flatpal" "${PKG_DIR}"
# Drop any stray __pycache__ left over from local runs.
find "${PKG_DIR}" -type d -name __pycache__ -exec rm -rf {} + 2>/dev/null || true

install -m 0644 "${SRC_DIR}/data/flatpal.desktop" "${DESKTOP_DIR}/flatpal.desktop"

installed_icons=()
for size in "${ICON_SIZES[@]}"; do
  src="${SRC_DIR}/data/flatpal-icon-${size}x${size}.png"
  if [[ -f "${src}" ]]; then
    dst_dir="${ICON_HICOLOR}/${size}x${size}/apps"
    mkdir -p "${dst_dir}"
    # Two filenames per size: `flatpal.png` for the .desktop Icon= entry,
    # `com.hawwwran.flatpal.png` so GNOME Shell can find the taskbar icon by
    # the running window's xdg-toplevel app_id (which matches our Adw
    # application_id).
    install -m 0644 "${src}" "${dst_dir}/flatpal.png"
    install -m 0644 "${src}" "${dst_dir}/com.hawwwran.flatpal.png"
    installed_icons+=("${dst_dir}/flatpal.png")
  fi
done

# Clean up artefacts from earlier installs that used a single-PNG approach.
rm -f "${ICON_HICOLOR}/scalable/apps/flatpal.svg"

cat > "${BIN_DIR}/flatpal" <<EOF
#!/usr/bin/env bash
# Launcher generated by install.sh
exec env PYTHONPATH="${APP_DIR}:\${PYTHONPATH:-}" python3 -m flatpal "\$@"
EOF
chmod 0755 "${BIN_DIR}/flatpal"

if command -v update-desktop-database >/dev/null 2>&1; then
  update-desktop-database "${DESKTOP_DIR}" >/dev/null 2>&1 || true
fi
if command -v gtk-update-icon-cache >/dev/null 2>&1; then
  gtk-update-icon-cache -f -t "${ICON_HICOLOR}" >/dev/null 2>&1 || true
fi

echo "Installed:"
echo "  ${BIN_DIR}/flatpal"
echo "  ${PKG_DIR}/  (Python package)"
echo "  ${DESKTOP_DIR}/flatpal.desktop"
echo "  ${#installed_icons[@]} icons across ${ICON_HICOLOR}/{16,24,32,48,64,96,128,192,256,512}x*"
echo "    (each as both flatpal.png and com.hawwwran.flatpal.png)"
echo
echo "Launch with: flatpal   (or search 'Flatpal' in your launcher)"

case ":${PATH}:" in
  *":${BIN_DIR}:"*) ;;
  *) echo
     echo "Note: ${BIN_DIR} is not on PATH in this shell. Open a new terminal or 'source ~/.profile'." ;;
esac
